new Leveragelp Query
elys-network/bindings pull request #362
Opened 2024-06-07 04:41 UTC by politeWall

- [x] Leveragelp Open and close estimation

2024-06-07 07:35 UTC, amityadav0 commented on scripts/queries.sh
> +
can we add function for `master_chef_pool_info` ?

2024-06-07 07:35 UTC, amityadav0 commented on scripts/queries.sh
> +    printf "\n# everagelp close estimation\n"
```suggestion
    printf "\n# leveragelp close estimation\n"
```

2024-06-07 07:35 UTC, amityadav0 commented on scripts/queries.sh
> +    ;;
do we need to add `master_chef_pool_info ` here too ?

2024-06-11 13:34 UTC, Wgil requested changes
Please check and fix both open and close estimation interfaces. They dont match

2024-06-11 13:34 UTC, Wgil commented on bindings/src/query_resp.rs
> +pub struct LeveragelpCloseEstResponse {
This is wrong. See https://github.com/elys-network/elys/pull/544/files#diff-608a4d4096e8cad7b23065a30151bc5cb22c87e505600789c15cd71c3a0c8d11R229

2024-06-12 16:14 UTC, Wgil approved these changes

2024-06-12 16:18 UTC, merged